services:
  mysql:
    image: mysql:8.4
    container_name: fruit-api-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fruitdb
      MYSQL_USER: fruituser
      MYSQL_PASSWORD: fruitpass

    ports:
      - "3308:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: fruit-api

    depends_on:
      - mysql

    environment:
      DB_URL: jdbc:mysql://mysql:3306/fruitdb
      DB_USER: fruituser
      DB_PASSWORD: fruitpass

    ports:
      - "8080:8080"

volumes:
  mysql_data: